### ISSUE TITLE
说正事专用issue

### ISSUE THREAD

**Issue by gigaflw** [vinx13/sjtuface-web#1]
现在干啥？

**Comment by vinx13** [comment]
group就暂时不用了吧
现在先
- 添加／删除 person
- 给person添加图片
- 识别
- 管理员登陆

**Comment by gigaflw** [comment]
怎么和我之前封装的那个facepp接起来？
我的想法是
我之前写的那个都封装在一个类里面了，
这里login成功之后就初始化一个对象放在`g`里面怎么样？

**Comment by gigaflw** [comment]
算了我先做前端吧……
后端逻辑该怎么写我搞不太清楚……

**Comment by vinx13** [comment]
login成功是在session中作标记

**Comment by gigaflw** [comment]
？？？？不理解发生了什么
我还是写前端去吧

**Comment by vinx13** [comment]
把代码模块化了一下而已

**Comment by gigaflw** [comment]
~~我们基于什么python版本？2还是3~~
原来我们一直在用python2吗……才发现

**Comment by gigaflw** [comment]
![image](https://cloud.githubusercontent.com/assets/13916180/17726951/6013cace-6488-11e6-8bee-72703f59113d.png)
??

**Comment by vinx13** [comment]
新的import的方式还没来得及改

**Comment by gigaflw** [comment]
那我改咯

**Comment by gigaflw** [comment]
~~`person`的`id`为什么是用户定的不是自增的？~~
`person`的`id`为什么unicode？它和`name`什么区别？
还有上传的图像放哪好？

**Comment by vinx13** [comment]
类似于学号和姓名，后续可能会有更多信息
上传的图像可以建一个static下的upload文件夹，记得重命名（把md5或者时间戳加上去）

**Comment by gigaflw** [comment]
好

**Comment by gigaflw** [comment]
终于……
页面能看了……

**Comment by gigaflw** [comment]
@vinx13 
facepp 的东西打算怎么放进来？

**Comment by vinx13** [comment]
$ python run.py
/usr/local/lib/python2.7/site-packages/flask_sqlalchemy/**init**.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')

什么情况？

**Comment by gigaflw** [comment]
[https://www.zhihu.com/question/41524822](url)
改了

**Comment by gigaflw** [comment]
我们真的可以在军训前结束吗？？
明天我把管理员登录写了，
training那一块都扔给你咯

**Comment by vinx13** [comment]
看来不能结束了～

**Comment by vinx13** [comment]
person delete在safari上不正常，会进入ajax-error分支
chrome可以哒

**Comment by gigaflw** [comment]
😱 我看看

**Comment by gigaflw** [comment]
好像是因为人名标签和删除按钮上都有单击事件，两者冲突了

现在好了

**Comment by vinx13** [comment]
现在基本能用了吧～

**Comment by gigaflw** [comment]
恩，我去把train和identify连进现在的页面里
